/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbc;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jpl7.*;

/**
 *
 * @author paulo
 */
public class Genero extends javax.swing.JFrame {
     static String asserts;
    /**
     * Creates new form Genero
     */
    public Genero(String asserts) {
        initComponents();
        this.asserts = asserts;
         

        this.setResizable(false);

        this.setLocationRelativeTo(null);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        animacao = new javax.swing.JRadioButton();
        aventura = new javax.swing.JRadioButton();
        comedia = new javax.swing.JRadioButton();
        drama = new javax.swing.JRadioButton();
        ficcao = new javax.swing.JRadioButton();
        guerra = new javax.swing.JRadioButton();
        musical = new javax.swing.JRadioButton();
        suspense = new javax.swing.JRadioButton();
        terror = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sbc/images/genero.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel2.setText("Sistemas Baseados em Conhecimento");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sbc/images/Sair.png"))); // NOI18N
        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sbc/images/next.png"))); // NOI18N
        jButton2.setText("Seguinte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Quais os seus géneros cinematográficos preferidos?");

        animacao.setText("Animação");
        animacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animacaoActionPerformed(evt);
            }
        });

        aventura.setText("Aventura");
        aventura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aventuraActionPerformed(evt);
            }
        });

        comedia.setText("Comédia");

        drama.setText("Drama");

        ficcao.setText("Ficção");

        guerra.setText("Guerra");

        musical.setText("Musical");

        suspense.setText("Suspense");
        suspense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suspenseActionPerformed(evt);
            }
        });

        terror.setText("Terror");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aventura)
                                            .addComponent(comedia))
                                        .addGap(167, 167, 167)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(guerra)
                                            .addComponent(ficcao))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(animacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(drama)
                                        .addGap(145, 145, 145)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(terror)
                                    .addComponent(suspense)
                                    .addComponent(musical)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 102, Short.MAX_VALUE)))
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(animacao)
                            .addComponent(drama)
                            .addComponent(musical))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aventura)
                            .addComponent(ficcao)
                            .addComponent(suspense))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(terror)
                            .addComponent(guerra)
                            .addComponent(comedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suspenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suspenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suspenseActionPerformed

    private void aventuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aventuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aventuraActionPerformed

    private void animacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animacaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(animacao.isSelected() || aventura.isSelected() || comedia.isSelected() || drama.isSelected() ||
            ficcao.isSelected() || guerra.isSelected() || musical.isSelected() || suspense.isSelected() || terror.isSelected()) {
            if (animacao.isSelected()){
                String genero = "animacao";
                this.asserts += "assert(fact("+genero+")),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (aventura.isSelected()){
                String genero = "aventura";
                this.asserts += "assert(fact("+genero+")),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();

            }

            if (comedia.isSelected()){
                String genero = "comedia";
                this.asserts += "assert(fact("+genero+")), assert(fact(ficcao)), assert(fact(musical)),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (drama.isSelected()){
                String genero = "drama";
                String genero2 ="terror";
                this.asserts += "assert(fact("+genero+")),assert(fact("+genero2+")),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (ficcao.isSelected()){
                String genero = "ficcao";
                this.asserts += "assert(fact("+genero+")),assert(fact(musical)), assert(fact(ficcao)),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (guerra.isSelected()){
                String genero = "guerra";
                this.asserts += "assert(fact("+genero+")),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (musical.isSelected()){
                String genero = "musical";
                this.asserts += "assert(fact("+genero+")),assert(fact(comedia)), assert(fact(ficcao)),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (suspense.isSelected()){
                String genero = "suspense";
                this.asserts += "assert(fact("+genero+")),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }

            if (terror.isSelected()){
                String genero = "terror";
                this.asserts += "assert(fact("+genero+")),assert(fact(drama)),";

                System.out.println(asserts);
                Preferidos preferidos = new Preferidos(asserts);
                preferidos.setVisible(true);
                this.dispose();
            }
        }
        else {
            JOptionPane.showMessageDialog(new JFrame(), "É necessário responder à pergunta antes de prosseguir!","Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Genero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Genero(asserts).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton animacao;
    private javax.swing.JRadioButton aventura;
    private javax.swing.JRadioButton comedia;
    private javax.swing.JRadioButton drama;
    private javax.swing.JRadioButton ficcao;
    private javax.swing.JRadioButton guerra;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton musical;
    private javax.swing.JRadioButton suspense;
    private javax.swing.JRadioButton terror;
    // End of variables declaration//GEN-END:variables
}
