import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jpl7.Query;
import sb.Ligacao;



public class EscolhaGenero extends javax.swing.JFrame {
        static String asserts;
        static String tipo;
        static String genero = "";
        
    /**
     * Creates new form EscolhaGenero
     */
    public EscolhaGenero(String asserts, String tipo) {
        initComponents();
        this.asserts = asserts;
        this.tipo = tipo;
        this.setSize(500, 400);

        // Não permite o redimensionamento da janela
        this.setResizable(false);

        // Mostra a centralização da janela
        this.setLocationRelativeTo(null);
        
        buttonGroup1.add(Opcao1);
        buttonGroup1.add(Opcao2);
        buttonGroup1.add(Opcao3);
        buttonGroup1.add(Opcao4);

        if(tipo.equals("filme")){
        Opcao1.setText("Homem Invisivel"); //Terror, Mistério, Ficçao cientifica
        Opcao2.setText("Frozen"); //Animação, Familia, Comédia, Aventura, Música
        Opcao3.setText("Top Gun - Ases Indomáveis"); //Ação, Romance, Drama
        Opcao4.setText("Last Days in The Vietnam"); //Documentário, História, Guerra
        }
        else if(tipo.equals("serie")){
        Opcao1.setText("The Walking Dead"); //Drama, Terror, Thriller, Ficção Científica
        Opcao2.setText("La Casa de Papel"); //Ação, Crime e Mistério, Romance, Policial 
        Opcao3.setText("Auschwitz: The Nazis and the Final Solution"); //Documentário, História, Guerra 
        Opcao4.setText("The Simpsons"); //Animação, Comédia,  Música 
        }
        else if(tipo.equals("indiferente")){
        Opcao1.setText("The Walking Dead"); //Drama, Terror, Thriller, Ficção Científica
        Opcao2.setText("La Casa de Papel"); //Ação, Crime e Mistério, Romance, Policial 
        Opcao3.setText("Last Days in The Vietnam"); //Documentário, História, Guerra
        Opcao4.setText("Frozen"); //Animação, Familia, Comédia, Aventura, Música
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Opcao1 = new javax.swing.JRadioButton();
        Opcao2 = new javax.swing.JRadioButton();
        Opcao3 = new javax.swing.JRadioButton();
        Opcao4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Faça a sua escolha!");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aaaaaaa.png"))); // NOI18N

        jButton1.setText("Seguinte");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Com qual destas opções se identifica mais?");

        Opcao1.setText("Opção1");
        Opcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Opcao1ActionPerformed(evt);
            }
        });

        Opcao2.setText("Opção2");

        Opcao3.setText("Opção3");

        Opcao4.setText("Opção4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Opcao2)
                            .addComponent(Opcao1)
                            .addComponent(Opcao4)
                            .addComponent(Opcao3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(Opcao1)
                .addGap(18, 18, 18)
                .addComponent(Opcao2)
                .addGap(18, 18, 18)
                .addComponent(Opcao3)
                .addGap(18, 18, 18)
                .addComponent(Opcao4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String opcao = "";

       // asserts = "assert(fact("+ tipo +")), assert(fact(nota_boa)), assert(fact(recente)),";
        
        if(!(Opcao1.isSelected() || Opcao2.isSelected() || Opcao3.isSelected() || Opcao4.isSelected())){
            JOptionPane.showMessageDialog(new JFrame(), "Selecione uma opcão!","Erro", JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(Opcao1.isSelected() && tipo.equals("filme")){
                genero = "Terror, Mistério, Ficçao cientifica"; //Homem Invisivel
            }
            if(Opcao1.isSelected() && (tipo.equals("serie") || tipo.equals("indiferente"))){
                genero = "Drama, Terror, Thriller, Ficção Científica"; //The Walking Dead
            }
            if(Opcao2.isSelected() && tipo.equals("filme")){
                genero = "Animação, Familia, Comédia, Aventura, Música"; //Frozen
            }
            if(Opcao2.isSelected() && (tipo.equals("serie") || tipo.equals("indiferente"))){
                genero = "Ação, Crime e Mistério, Romance, Policial"; //La Casa de Papel
            }
            if(Opcao3.isSelected() && tipo.equals("filme")){
                genero = "Ação, Romance, Drama"; //Top Gun
            }
            if(Opcao3.isSelected() && tipo.equals("serie")){
                genero = "Documentário, História, Guerra"; //Auschwitz
            }
            if(Opcao3.isSelected() && tipo.equals("indiferente")){
                genero = "Documentário, História, Guerra"; //Last Days in The Vietnam
            }
            if(Opcao4.isSelected() && tipo.equals("filme")){
                genero = "Documentário, História, Guerra"; //Last Days in The Vietnam
            }
            if(Opcao4.isSelected() && tipo.equals("serie")){
                genero = "Animação, Comédia,  Música"; //The Simpsons
            }
            if(Opcao4.isSelected() && tipo.equals("indiferente")){
                genero = "Animação, Familia, Comédia, Aventura, Música"; //Frozen
            }
            
       /* Query q1 = new Query(asserts + ", obtem(P)");
        System.out.println(q1.toString());
        q1.hasSolution();
        q1.close();*/

        EscolhaGenero2 eg = new EscolhaGenero2(asserts, tipo, genero);
        eg.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Opcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Opcao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Opcao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main1(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaGenero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new EscolhaGenero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Opcao1;
    private javax.swing.JRadioButton Opcao2;
    private javax.swing.JRadioButton Opcao3;
    private javax.swing.JRadioButton Opcao4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
